apiVersion: v1
kind: Secret
metadata:
    name: tierlist-secrets
    namespace: tierlist
type: Opaque
stringData:
    DISCORD_CLIENT_ID: ENC[AES256_GCM,data:nx6kupne9uwtrcUbMRlORhcfkw==,iv:2JDI8DyjcIkDDg+lcyrTUSJWVCVrZeXWMA4ZipvkPrs=,tag:3uetu9dWfLhCaP82CbVI0w==,type:int]
    DISCORD_CLIENT_SECRET: ENC[AES256_GCM,data:QPJGU8Z2HXzQxUTTeBHQIZFdXcua7ovmleyypOEhnRU=,iv:uKBFsusBe5AzHyy6q5h57XPBE9Dno9OnrL/0cAurSyc=,tag:H5JDtpJ33CejKr/5CNVdGQ==,type:str]
    ADMIN_DISCORD_IDS: ENC[AES256_GCM,data:ouJL1mBd90sOFCTH9klcMM6u,iv:T4vyexh7B8Vc9YmGls7IItVfl0jIQQcltb292A/0aSM=,tag:monoETo8KVpINWDGiWuW2Q==,type:int]
    JWT_SECRET: ENC[AES256_GCM,data:h3Nut9wALj+bJOqMG17dLKp2Dwi2pU0SDELwhR1Q43E=,iv:M25lefLUdtP6U4zIkzn/2lQcbnUNd+nOENc8+4ZBDak=,tag:JiiR6E1K8HQEJV25BjnGrg==,type:str]
sops:
    age:
        - recipient: age17e75hk8vvxc6zk30lt0dd34xqg5mfdgkzxzxzh4r75q50hk96egqkk25lz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdUx4eDdBZTgzUjhPekR2
            UGg4Tm9GSDhXVlVEZXpvS2JRT1QvU2dPU2xNCmc0cmpicGNvUjllWk1QYk1XWmR4
            NVRXYUg2ZllFbVNQNnBWc0hSd3ZZWGsKLS0tIGFtODZwK0t3WXdEWnBuQ253Qmdx
            RE55b0JIWW5tdi91aTBzYmw3aXY2Q2cKWp/6jIGikubKyqTTuF9EJxfVAbY9BYBu
            InxC7oNU1zsR+PqV077zAmC1mE+7keX0P9O99TjoIizS6yS9kMnA8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T08:22:06Z"
    mac: ENC[AES256_GCM,data:zvD9mZdWuz93/UMn1wey+Lsvv3EZ3Z9gFSpc/QwOSIWVQL5q4OzaEsRpOHCbY8YsEJqZFne/AsKikXFEv5daxlTr6yOlat6hffiAMpbF1ncveOaEC05+qA4PaGqz7Sdq79sscl1U+wMjRKglBJj+VVYgU1/FSRdaloC1SDQ48t0=,iv:Z49I6lsRezisABLH7u+WbLU3skrWf2W7W3A7Qa+nGbI=,tag:iitWkm9OEZLrO5tkKoB03w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
