apiVersion: v1
kind: Secret
metadata:
    name: tierlist-secrets
    namespace: tierlist
type: Opaque
stringData:
    DISCORD_CLIENT_ID: ENC[AES256_GCM,data:ZZQ9WEMImHq2k4lokTd3wHaqPQ==,iv:GxHwL2XBv/XeoEX1p9DsL11DEakkJMSCoT28kmKe6J0=,tag:oAeuEPD6xR/PUL3dI+RmMw==,type:str]
    DISCORD_CLIENT_SECRET: ENC[AES256_GCM,data:KJqPtnfmg6q2SgXn1ieZ9ErVPdEFQmKSONk8xw5rpvI=,iv:5qqtdzHXJmGFctmU9hL2kbzMcTSO8v2P0HVo8WJU15s=,tag:cOWbOOt4OKhU0K6GgiuOQw==,type:str]
    ADMIN_DISCORD_IDS: ENC[AES256_GCM,data:mJtM+Y62YCXjqqaZsvSfQTxz,iv:S73R0NlztodF8hMvJiTDavbcpSUqBNclVqnQREJNi4E=,tag:6eAIvztypNZBHIH+Uxk10g==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:aBZIJOcD1Nzsm9oxE8jIV1X0Rw9XMZny2XRXJfTkLou/J0cLeO8W4geaEww=,iv:+BeTX4agNxgi7WGkFkCHtzAggtXugsT/WTcAQKZDC54=,tag:sBUJ0cvgr2zuuXZ+zAfOxA==,type:str]
sops:
    age:
        - recipient: age17e75hk8vvxc6zk30lt0dd34xqg5mfdgkzxzxzh4r75q50hk96egqkk25lz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVWtNZ2orRDFuZTF6VVli
            MktGdFZIUlZpTnNsbUNUK2w0bXlYTkdGeFh3CjIwc25uUVJvZ0RwYUpmTDg0dStH
            SFZoazJrL0FMSVY0U0hhcWliYXJPQ1UKLS0tIEp3dkNsSFdyUExkZTN4c09BbDRh
            aHFpNjdNSG1HcEN4UGNkL2xOcDBoZ28K9BTGnF0utb9Ag3IGoIDp3zT60P7mbCZq
            pAUVwift5mDqAyf/1/aBw7lVcwwf9piGA9MWMwpjem4vebzzT4/kww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T12:08:55Z"
    mac: ENC[AES256_GCM,data:iAqNscCMEOrrDd4bhOT2bHyA9fGMZB57vXgTeBHxMnNwCR1gUemlRKzPQ/GarSZieS/NQAZFOqFKIp73ufrjc7+fPte0Cy0AEbo1pG8WLbqUqzO4TAYVz8Jijd1uVu94syxg4To8Y05/xTofN3f8VIdl6RaV61ZB0ep0EyaXSXM=,iv:YhFUKLdVk4YPciFuLAvw3bcsRH+GqnlQ+pq2DpHWjTc=,tag:N+bzSiL0TI6fJdWvDA8nbg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
